travis:
  secure:
    BINSTAR_TOKEN: L+JGN9n6uRcYzOR/2FSSAeTlC89rRQTnQGgQ6nC4Njyt5sOdfFSZ8DtxFnJz6hu6SFuPqRVd/oH22hQ5U6s+pO/Ux93ZViUiE+zY8hw+1YOHcpHtz1Tt4/v3Ruz1eHw25nkP01wuVmAl8hEuDYhAgYsD3ay+nmxHbqxiRDLoEMXeLuXBUPW7dm/nM2myFyekNnAL8ywbrVEZFaHoXT2ODiPckUBJmgKW7tE+ia2dyGEZTQjaq50tf4QQjOHCgkwKeRqEn+KFMTOUU545OgGk4dik5H1V/PtbO9r0VKizR3iQC6wr6e1Yw6uTqZn0WvSALsYek9Oo03h+JvT8LD9g3anAsiG06Or8Jr3GbWEDrGbvDEzL2lo1wuK0l0IQ5YYQm/aq7H/k/tE+hz4yzFSXLo0MMPqOmf6m0u/dQlOmQU6rl2uaQt3LdgO+nSpBYaym6Pz2areH7bIA0txvZXoUnfAV0rN9PQkoAeecnWZWjJiVtJWQXFTrl+RXyiPLzFPvfOvtk6fDGdekzfHD4Vq84RlLh4ZRyeHXQIkdnTjl6plzqkw+DJ8XkjEaVyfH7kd6tdwN7SG6sFapTtlXTQc+bwvuDHJ8y/CrMN8ngv06464dNtu0lOMul2kQsXK5WCS/nGn5jwcx4ZoQqd1gOq2/83hMz2tOSFA1HPsEhiOedoM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
