travis:
  secure:
    BINSTAR_TOKEN: BBPkRYtmMhwoW+29rai7OSkCnpzdT9SuhlKcC4bVbxF4qR6AazWoMLagb5LyNFEvDQ/FhRc455NSeUAOOfNYkZTutdyysLBZQCyhulDz05C1ktYex7+utAVBg7b3YLQ5GfhQnUXBI54Rgpo4xGDnQHs5ujztSyt9flQ+G6gyOA7lV4BeCQpAtNjGJ+gKGwv2qeKy/LpazjhXGMoqNX6NWjfWSNYQLtxYMJ4hT71ekyFBympSMIxC/4pHuexkyCNHL9Z7vc+itIws2vvW5xSug+n8dhQgpDIgw6AD0Cs5ofysCbVHm4Za2oUTHOFVM7WGSfCUFGIp2HMIo7OgpMU6uZD0mavoOQ+gwOkzKomx6GAqj++/oac26mgTGXo/Co8UM5TDM0JMu+JAaZcsGFtKbH1Yqs3NRmmF+1T82EvQ175CjWrjTgH5l7YR6GF3MVj/FaiD5woOBqUnoqqaKm6rictoAx+8pjlN0oOQHuClS4UkO6+v33ms0/m/dLtnxeoXUqrxsQ8xPBUkMgZErYEerva/dif6YM5gmQ0mp/N5fA/ymOJhzpy4C/5s5JgSuU0/vqAgfgNduuPVCCCP7AiCelX6Abovw0F8P9QlosdDrU9fv5DqmUR8eNfyIV/AWuvUJhVQnIECGen2j5VGJrj0E/HOtV+8/h5/0ds91FPRhk8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
